config/routes.rb
Mun::Application.routes.draw do

  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "users"
  resources :users

  namespace :admin do
    match '/' => 'users#index'
    resources :users
    resources :news
  end

  get "static_pages/index"

  root :to => "static_pages#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here.
    user ||= User.new # guest user (not logged in)
    # a signed-in user can do everything
    if user.has_role? :admin
      # an admin can do everything
      can :manage, :all
    elsif user.has_role? :staff
      # an editor can do everything to documents and reports
      can :manage, [News, Report]
      # but can only read, create and update charts (ie they cannot
      # be destroyed or have any other actions from the charts_controller.rb
      # executed)
      can [:read, :create, :update], Chart
      # an editor can only view the annual report
      can :read, AnnualReport
    elsif user.has_role? :registered
      can :read, [News, Report, Chart]
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title, :user_id

  belongs_to :user
end

app/models/user.rb
require 'role_model'

class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # For more info on RoleModel, go to:  https://github.com/martinrehfeld/role_model
  include RoleModel

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :roles, :roles_mask

  has_many :news

  # optionally set the integer attribute to store the roles in,
  # :roles_mask is the default
  roles_attribute :roles_mask

  # declare the valid roles -- do not change the order if you add more
  # roles later, always append them at the end!
  roles :admin, :registered, :staff

  before_save :default_role

  # Default role is "Registered"
  def default_role
    if self.roles.empty?
      self.roles = [:registered]
    end

  end

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  #layout "admin"
  before_filter :verify_admin

  def verify_admin
    :authenticate_user!
    #redirect_to root_url unless has_role?(current_user, 'admin')
  end

  def current_ability
    @current_ability ||= Ability.new(current_user)
  end
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < Admin::AdminController
  load_and_authorize_resource
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])
    @news.user = current_user

    respond_to do |format|
      if @news.save
        format.html { redirect_to admin_news_index_path, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to admin_news_url, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to admin_news_index_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.attributes = params[:user]
    @user.roles = params[:user][:roles] if params[:user]
    respond_to do |format|
      if @user.save
        flash[:notice] = flash[:notice].to_a.concat @user.errors.full_messages
        format.html { redirect_to admin_users_path, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        flash[:notice] = flash[:notice].to_a.concat @user.errors.full_messages
        format.html { render :action => "new"}
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_path, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  #def has_role?(current_user, role)
   # return !!current_user.roles.find_by_name(role.to_s.camelize)
  #end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/news/_form.html.erb
<%= form_for [:admin, @news] do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/news/edit.html.erb
<%= form_for [:admin, @news], :url => admin_news_path(@news), :html => { :class => "form-horizontal", :id => "edit_news" } do |f| -%>
    <input name="_method" type="hidden" value="put" />
    <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/admin/news/index.html.erb
<h1>Listing news</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news.each do |news| %>
  <tr>
    <td><%= news.title %></td>
    <td><%= news.content %></td>
    <td><%= news.user_id %></td>
    <td><%= link_to 'Show', admin_news_path(news) %></td>
    <td><%= link_to 'Edit', edit_admin_news_path(news) %></td>
    <td><%= link_to "Destroy", admin_news_path(news), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New News', new_admin_news_path %>

app/views/admin/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_news_index_path %>

app/views/admin/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @news.title %>
</p>

<p>
  <b>Content:</b>
  <%= @news.content %>
</p>

<p>
  <b>User:</b>
  <%= @news.user_id %>
</p>


<%= link_to 'Edit', edit_admin_news_path(@news) %> |
<%= link_to 'Back', admin_news_index_path %>

app/views/admin/users/_form.html.erb
<div class="control-group">
  <%= f.label :email, t("activerecord.attributes.user.email", :default => "Email"), :class => 'control-label' %>
  <div class="input">
    <%= f.text_field :email, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :password, t("activerecord.attributes.user.password", :default => "password"), :class => 'control-label' %>
  <div class="input">
    <%= f.password_field :password, :class => 'password_field' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :Password, t("activerecord.attributes.user.password_confirmation", :default => "password_confirmation"), :class => 'control-label' %>
  <div class="input">
    <%= f.password_field :password_confirmation, :class => 'password_field' %>
  </div>
</div>

<% for role in User.valid_roles %>
    <div class ="control-group">
      <%= f.label role , :class => 'control-label' %>
      <div class="controls">
        <%= check_box_tag "user[roles][]", role, @user.roles.include?(role) %>
      </div>
    </div>
<% end %>


<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> or
  <%= link_to "Cancel", admin_users_path %>
</div>

app/views/admin/users/edit.html.erb
<%= form_for [:admin, @user], :url => admin_user_path(@user), :html => { :class => "form-horizontal", :id => "edit_user" } do |f| -%>
    <input name="_method" type="hidden" value="put" />
    <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/admin/users/index.html.erb
<h1>Users</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>
      <%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>
    </th>
    <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| -%>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.email, admin_user_path(user) %>
        </td>
        <td><%= user.created_at %></td>
        <td>
          <%= link_to "Show", admin_user_path(user) %>
          <%= link_to "Edit", edit_admin_user_path(user) %>
          <%= link_to "Destroy", admin_user_path(user), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
        </td>
      </tr>
  <% end -%>
  </tbody>
</table>

<%= link_to "New", new_admin_user_path, :class => 'btn btn-primary' %>

app/views/admin/users/new.html.erb
<%= form_for [:admin, @user], :url => admin_users_path, :html => { :class => :form } do |f| -%>
    <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/admin/users/show.html.erb
<label class="label"><%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>:</label>
<p><%= @user.email %></p>

<div class="form-actions">
  <%= link_to "Back", admin_users_path, :class => 'btn'  %>
  <%= link_to "Edit", edit_admin_user_path(@user), :class => 'btn' %>
  <%= link_to "Delete", admin_user_path(@user), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mun" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">WMHMUN XXVII</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "About", "/path1"  %></li>
              <li><%= link_to "Committees", "/path2"  %></li>
              <li><%= link_to "Schedule", "/path3"  %></li>
              <li><%= link_to "Registration", "/path4"  %></li>
              <li><%= link_to "Travel & Accomodations", "/path5"  %></li>
              <li><%= link_to "Contact Us", "/path6"  %></li>
              <li><%= link_to "FAQ", "/path7"  %></li>
              <li><%= link_to "Register", new_user_registration_path  %></li>
              <li><%= link_to "Login", user_session_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>


    <% if user_signed_in? %>
      <% #link_to "My Profile", user_root_path%>
      <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    <%end%>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "About", "/path1"  %></li>
              <li><%= link_to "Committees", "/path2"  %></li>
              <li><%= link_to "Schedule", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/static_pages/index.html.erb
<h1>Static#index</h1>
<p>Find me in app/views/static/index.html.erb</p>